### PR TITLE
GraalVM 22.3.0 supports Java 19

### PR DESCRIPTION
**Pull request by demidko**
#524 fixed

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/gradle-graal](https://github.com/palantir/gradle-graal), @demidko! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by demidko** [comment]
> Thanks for your interest in [palantir/gradle-graal](https://github.com/palantir/gradle-graal), @demidko! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

Yes, I sign

**Comment by mageddo** [comment]
Hey can you generate a snapshot or something like?

**Comment by demidko** [comment]
@asvoboda can you approve?

**Pull request closed without merging**
